port: 8001
mongo_address: localhost
mongo_port: 27017
mongo_db: test
mongo_user: peter
mongo_pass: peter
# This part is optional, leave it commented out to copy all information to the database
# or set the field names you want to store.
database_ignore:
    - SQ
    - KW
